-- MySQL Script generated by MySQL Workbench
-- Fri Nov 25 14:14:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema groupAKainos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema groupAKainos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `groupAKainos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `groupAKainos` ;

-- -----------------------------------------------------
-- Table `groupAKainos`.`jobBandLevel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groupAKainos`.`jobBandLevel` ;

CREATE TABLE IF NOT EXISTS `groupAKainos`.`jobBandLevel` (
  `bandLevelId` INT NOT NULL AUTO_INCREMENT,
  `BandLevel` INT NULL DEFAULT NULL,
  `BandName` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`bandLevelId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `groupAKainos`.`jobCapabilities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groupAKainos`.`jobCapabilities` ;

CREATE TABLE IF NOT EXISTS `groupAKainos`.`jobCapabilities` (
  `capabilityId` INT NOT NULL AUTO_INCREMENT,
  `capabilityName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`capabilityId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `groupAKainos`.`jobFamily`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groupAKainos`.`jobFamily` ;

CREATE TABLE IF NOT EXISTS `groupAKainos`.`jobFamily` (
  `jobFamilyId` INT NOT NULL AUTO_INCREMENT,
  `capabilityId` INT NULL DEFAULT NULL,
  `familyName` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`jobFamilyId`),
  INDEX `capabilitiesId_idx` (`capabilityId` ASC) VISIBLE,
  CONSTRAINT `capabilitiesId`
    FOREIGN KEY (`capabilityId`)
    REFERENCES `groupAKainos`.`jobCapabilities` (`capabilityId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `groupAKainos`.`job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groupAKainos`.`job` ;

CREATE TABLE IF NOT EXISTS `groupAKainos`.`job` (
  `jobId` INT NOT NULL AUTO_INCREMENT,
  `jobName` VARCHAR(50) NULL DEFAULT NULL,
  `jobResponsibility` VARCHAR(1500) NULL DEFAULT NULL,
  `specification` VARCHAR(500) NULL DEFAULT NULL,
  `specSummary` VARCHAR(1500) NULL DEFAULT NULL,
  `bandLevelId` INT NULL DEFAULT NULL,
  `jobFamilyId` INT NULL DEFAULT NULL,
  `capabilityId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`jobId`),
  INDEX `familyNameId_idx` (`jobFamilyId` ASC) VISIBLE,
  INDEX `bandLevelId_idx` (`bandLevelId` ASC) VISIBLE,
  INDEX `capabilityId_idx` (`capabilityId` ASC) VISIBLE,
  CONSTRAINT `bandLevelId`
    FOREIGN KEY (`bandLevelId`)
    REFERENCES `groupAKainos`.`jobBandLevel` (`bandLevelId`),
  CONSTRAINT `capabilityId`
    FOREIGN KEY (`capabilityId`)
    REFERENCES `groupAKainos`.`jobCapabilities` (`capabilityId`),
  CONSTRAINT `familyNameId`
    FOREIGN KEY (`jobFamilyId`)
    REFERENCES `groupAKainos`.`jobFamily` (`jobFamilyId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `groupAKainos`.`jobTraining`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groupAKainos`.`jobTraining` ;

CREATE TABLE IF NOT EXISTS `groupAKainos`.`jobTraining` (
  `jobTrainingId` INT NOT NULL AUTO_INCREMENT,
  `courseName` VARCHAR(255) NULL DEFAULT NULL,
  `jobBandId` INT NULL DEFAULT NULL,
  `trainingLevel` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`jobTrainingId`),
  INDEX `jobBandId_idx` (`jobBandId` ASC) VISIBLE,
  CONSTRAINT `jobBandId`
    FOREIGN KEY (`jobBandId`)
    REFERENCES `groupAKainos`.`jobBandLevel` (`bandLevelId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `groupAKainos`.`competency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groupAKainos`.`competency` ;

CREATE TABLE IF NOT EXISTS `groupAKainos`.`competency` (
  `competencyId` INT NOT NULL AUTO_INCREMENT,
  `competencyName` VARCHAR(50) NULL,
  PRIMARY KEY (`competencyId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupAKainos`.`competency_band`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groupAKainos`.`competency_band` ;

CREATE TABLE IF NOT EXISTS `groupAKainos`.`competency_band` (
  `competencyBandId` INT NOT NULL AUTO_INCREMENT,
  `bandLevelId` INT NULL,
  `competencyId` INT NULL,
  `subheading` VARCHAR(120) NULL,
  `information` VARCHAR(600) NULL,
  PRIMARY KEY (`competencyBandId`),
  INDEX `competencyId_idx` (`competencyId` ASC) VISIBLE,
  INDEX `bandId_idx` (`bandLevelId` ASC) VISIBLE,
  CONSTRAINT `competencyId`
    FOREIGN KEY (`competencyId`)
    REFERENCES `groupAKainos`.`competency` (`competencyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bandId`
    FOREIGN KEY (`bandLevelId`)
    REFERENCES `groupAKainos`.`jobBandLevel` (`bandLevelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
