-- MySQL Script generated by MySQL Workbench
-- Wed Nov 23 12:10:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema groupAKainos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema groupAKainos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `groupAKainos` DEFAULT CHARACTER SET utf8 ;
USE `groupAKainos` ;

-- -----------------------------------------------------
-- Table `groupAKainos`.`jobCapabilities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groupAKainos`.`jobCapabilities` ;

CREATE TABLE IF NOT EXISTS `groupAKainos`.`jobCapabilities` (
  `capabilityId` INT NOT NULL AUTO_INCREMENT,
  `capabilityName` VARCHAR(45) NULL,
  PRIMARY KEY (`capabilityId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupAKainos`.`jobFamily`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groupAKainos`.`jobFamily` ;

CREATE TABLE IF NOT EXISTS `groupAKainos`.`jobFamily` (
  `jobFamilyId` INT NOT NULL AUTO_INCREMENT,
  `capabilityId` INT NULL,
  `familyName` VARCHAR(100) NULL,
  PRIMARY KEY (`jobFamilyId`),
  INDEX `capabilitiesId_idx` (`capabilityId` ASC) VISIBLE,
  CONSTRAINT `capabilitiesId`
    FOREIGN KEY (`capabilityId`)
    REFERENCES `groupAKainos`.`jobCapabilities` (`capabilityId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupAKainos`.`jobBandLevel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groupAKainos`.`jobBandLevel` ;

CREATE TABLE IF NOT EXISTS `groupAKainos`.`jobBandLevel` (
  `bandLevelId` INT NOT NULL AUTO_INCREMENT,
  `BandLevel` INT NULL,
  `BandName` VARCHAR(15) NULL,
  `capabilityId` INT NULL,
  PRIMARY KEY (`bandLevelId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupAKainos`.`job`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groupAKainos`.`job` ;

CREATE TABLE IF NOT EXISTS `groupAKainos`.`job` (
  `jobId` INT NOT NULL AUTO_INCREMENT,
  `jobName` VARCHAR(50) NULL,
  `jobResponsibility` VARCHAR(45) NULL,
  `specification` VARCHAR(500) NULL,
  `bandLevelId` INT NULL,
  `jobFamilyId` INT NULL,
  `capabilityId` INT NULL,
  PRIMARY KEY (`jobId`),
  INDEX `familyNameId_idx` (`jobFamilyId` ASC) VISIBLE,
  INDEX `bandLevelId_idx` (`bandLevelId` ASC) VISIBLE,
  INDEX `capabilityId_idx` (`capabilityId` ASC) VISIBLE,
  CONSTRAINT `familyNameId`
    FOREIGN KEY (`jobFamilyId`)
    REFERENCES `groupAKainos`.`jobFamily` (`jobFamilyId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bandLevelId`
    FOREIGN KEY (`bandLevelId`)
    REFERENCES `groupAKainos`.`jobBandLevel` (`bandLevelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `capabilityId`
    FOREIGN KEY (`capabilityId`)
    REFERENCES `groupAKainos`.`jobCapabilities` (`capabilityId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupAKainos`.`jobTraining`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `groupAKainos`.`jobTraining` ;

CREATE TABLE IF NOT EXISTS `groupAKainos`.`jobTraining` (
  `jobTrainingId` INT NOT NULL AUTO_INCREMENT,
  `courseName` VARCHAR(255) NULL,
  `jobBandId` INT NULL,
  `trainingLevel` VARCHAR(45) NULL,
  PRIMARY KEY (`jobTrainingId`),
  INDEX `jobBandId_idx` (`jobBandId` ASC) VISIBLE,
  CONSTRAINT `jobBandId`
    FOREIGN KEY (`jobBandId`)
    REFERENCES `groupAKainos`.`jobBandLevel` (`bandLevelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
