-- MySQL Script generated by MySQL Workbench
-- Tue Nov 22 14:15:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- USE `mydb` ;

 USE `groupAKainos` ;


-- -----------------------------------------------------
-- Table `groupAKainos`.`job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupAKainos`.`job` (
	`jobId` INT NOT NULL AUTO_INCREMENT,
	`jobName` VARCHAR(50) NULL,
	`jobResponsibility` VARCHAR(45) NULL,
	`specification` text NULL,


  PRIMARY KEY (`jobId`))
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `groupAKainosjobjobId`.`jobCapabilities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupAKainos`.`jobCapabilities` (
  `capabilityId` INT NOT NULL AUTO_INCREMENT,
  `capabilityName` VARCHAR(45) NULL,
  `jobId` INT NULL,
  PRIMARY KEY (`capabilityId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupAKainos`.`jobFamily`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupAKainos`.`jobFamily` (
  `jobFamilyId` INT NOT NULL AUTO_INCREMENT,
  `capabilityId` INT NULL,
  `familyName` VARCHAR(100) NULL,
  PRIMARY KEY (`jobFamilyId`),
  INDEX `capabilitiesId_idx` (`capabilityId` ASC) VISIBLE,
  CONSTRAINT `capabilitiesId`
    FOREIGN KEY (`capabilityId`)
    REFERENCES `groupAKainos`.`jobCapabilities` (`capabilityId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupAKainos`.`jobBandLevel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupAKainos`.`jobBandLevel` (
  `bandLevelId` INT NOT NULL AUTO_INCREMENT,
  `BandLevel` INT NULL,
  `BandName` VARCHAR(15) NULL,
  `capabilityId` INT NULL,
  PRIMARY KEY (`bandLevelId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupAKainos`.`jobCompetencies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupAKainos`.`jobCompetencies` (
  `jobCompetenciesId` INT NOT NULL,
  PRIMARY KEY (`jobCompetenciesId`))
ENGINE = InnoDB;


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
